name: Run Linting and Formatting checks
on: [push]
jobs:
  Linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Set the Python version(s) to run the tests with
        python-version: [3.9] # [3.7, 3.8, 3.9]
    steps:
      - name: Checking out code from the repository
        uses: actions/checkout@v2

      - name: Lint the code with black
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
